version: '3.8'
services:
  db:
    image: postgres:14.2-bullseye
    restart: always
    hostname: localhost
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: report_cruncher
    ports:
      - "5432:5432"
  report_cruncher:
    build:
      context: ./
      dockerfile: Dockerfile
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    depends_on:
      - db
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "report_cruncher"
      POSTGRES_PORT: "5432"
      POSTGRES_HOST: "db"
      OPENAI_API_KEY: ""
    ports:
      - "8000:8000"
